### ISSUE TITLE
Provide the capacity to assigne  and label issues

### ISSUE THREAD

**Issue by vturpin** [OceanOPS/helpdesk#14]
### Context/theme

Other (please specify)

### Other context (if applicable)

Github config

### Description of the desired feature

I would like to have the capacity to assigne and label the issue I submit.
So far I can't. I don't see the little wheel on the right and side vertical menu.

**Comment by anthoninlize** [comment]
Functionality enabled for OceanOPS team in the following repos: helpdesk, metadata-standard, web-dashboard
