### ISSUE TITLE
Unable to change GTS-ID.

### ISSUE THREAD

**Issue by KarlShepherdson** [OceanOPS/helpdesk#18]
### Context/theme

SOT

### Describe the bug

For Cable Retriever ship, I'm unable to change the GTS-ID from its ship call sign to the SOT-ID. I get "GTS ID: This identifier is no longer editable". Please advise/help. Thanks.

**Comment by KarlShepherdson** [comment]
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/132067244/235141819-7d76bd15-a19d-48f6-999a-352f1ea78fa8.png)

**Comment by MKrieger29** [comment]
Hello, I will update this information directly in the database. 
For this station, do you need to keep: 

- GTS id = S6OM (until date1) + JDWV7LP (from date2). In case, please send me the dates.  
- Or only GTS id = JDWV7LP ? 

If you need to update GTS ids for other stations in OceanOPS, don't hesitate to ask us (send us a list in another GitHub issue) and we will do it. 
Thanks

**Comment by KarlShepherdson** [comment]
Thanks for getting back to me so very quickly. It is much appreciated.
The GTS ID change date should be set as yesterday please, 27th April 2023. The ship is now reporting with its SOT-ID (previously used it's ship call sign).

Much appreciate your help once again,

Karl.

Karl Shepherdson BSc(Hons) Cert. Ed. FRMetS    Pronouns: he/him/his.
Observations: Regional Network Manager / Port Met. Officer (Northern England)
Met Office  Unit 3  Holland Business Park  Spa Lane  Lathom  Lancashire  L40 6LN  United Kingdom
Tel: +44 (0)3301351375 or +44 (0)7900737014
Email: ***@***.******@***.***>  Website: www.metoffice.gov.uk<http://www.metoffice.gov.uk/>

**Comment by KarlShepherdson** [comment]
Thanks for getting back to me so very quickly. It is much appreciated.
The GTS ID change date should be set as yesterday please, 27th April 2023. The ship is now reporting with its SOT-ID (previously used it’s ship call sign).

Much appreciate your help once again,

Karl.

Karl Shepherdson BSc(Hons) Cert. Ed. FRMetS    Pronouns: he/him/his.
Observations: Regional Network Manager / Port Met. Officer (Northern England)
Met Office  Unit 3  Holland Business Park  Spa Lane  Lathom  Lancashire  L40 6LN  United Kingdom
Tel: +44 (0)3301351375 or +44 (0)7900737014
Email: [karl.shepherdson@metoffice.gov.uk](mailto:karl.shepherdson@metoffice.gov.uk)  Website: [www.metoffice.gov.uk](http://www.metoffice.gov.uk/)

**Comment by MKrieger29** [comment]
Thank you for the precision, I upadted the records for this station in the OceanOPS DB: 
(with the gts id and the start date for each id)
![image](https://user-images.githubusercontent.com/74649916/235159181-0fda1cad-2a52-479e-b829-e171026039d8.png)

**Comment by KarlShepherdson** [comment]
Thank you :) Perfect.

Karl.

Karl Shepherdson BSc(Hons) Cert. Ed. FRMetS    Pronouns: he/him/his.
Observations: Regional Network Manager / Port Met. Officer (Northern England)
Met Office  Unit 3  Holland Business Park  Spa Lane  Lathom  Lancashire  L40 6LN  United Kingdom
Tel: +44 (0)3301351375 or +44 (0)7900737014
Email: ***@***.******@***.***>  Website: www.metoffice.gov.uk<http://www.metoffice.gov.uk/>
