### ISSUE TITLE
Float under Ice

### ISSUE THREAD

**Issue by vturpin** [OceanOPS/helpdesk#2]
### Context/theme

Argo

### Description of the desired feature

Floats deployed near the ice may not surface within 2 or 3 years. The Argo notification system send message to the program manager in case of no data XX month after the deployment.
I would like a feature that take this in consideration to limit notifications in that case.

### Suggested solution

I see two solutions: 
*Before the information is made available properly in the meta.nc file.*
Create a tick box in the edit section of the float to notify this float is drifting under this ice. When this box is selected, the "no data" notification system is turned of for 2 years.

*When this information is made available in the meta.file,*
then it will be taken into account and automatically registered in the system. 

### Alternatives considered

One the Technical coordination side, I will promote the idea of a new vocab for ice detection software.

### Additional context

This evolution will impact the status of the float. 
A float deployed under ice can not be OPERATIONAL until we receive data. It should remain ERGISTERED with the 'orfan' notification system turned off for 3 years.
In the inspect section of the float, the under ice status should be visible in the timeline.

**Comment by anthoninlize** [comment]
Floats with a status ICED in OceanOPS are now ignored for those notifications.

This has to be done manually by @MKrieger29 or myself while this can be implemented in the website (platform > location status).

Done for 6903146 following this issue report.
