### ISSUE TITLE
DBCP vandalism map

### ISSUE THREAD

**Issue by anthoninlize** [OceanOPS/helpdesk#6]
### Context/theme

DBCP

### Description of the desired feature

DBCP vandalism map for next week

**Comment by MKrieger29** [comment]
![DBCP_Vandalism2021-2022](https://user-images.githubusercontent.com/74649916/198578929-2eed84f1-32d7-4885-9960-5ced902de12d.png)

Here is the 2021 2022 map for DBCP vandalism
