### ISSUE TITLE
reduce size of dots - monthly map - Telecom Type - Argo

### ISSUE THREAD

**Issue by vturpin** [OceanOPS/helpdesk#7]
### Context/theme

Argo

### Describe the bug

It is not really a bug, more a comment.

- The dots on the "telecom type" monthly map are too big.
- Same for "Age"
- Same for "Kaharoa deployments"
- Same for "deployment plans"

Is it possible to reduce the size of the dot to a size similar to the "network" map?

### To reproduce

Static map -> telecom type

This is not high priority ;)

**Comment by anthoninlize** [comment]
Done for the maps listed, will be effective on next iteration
